apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0001
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 storageClassName: slow
 hostPath:
  path: /opt/openshift_pv/pv0001
# nfs:
#   server: 10.5.18.122
#   path: /var/nfs-data/pv0001
