apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0001
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 storageClassName: slow
 nfs:
   server: 10.5.18.122
   path: /var/nfs-data/pv0001
